apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}-config
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen {{ .Values.nginxConfig.server.listen }};
        server_name {{ .Values.nginxConfig.server.server_name }};
        
        location {{ .Values.nginxConfig.server.location }} {
          root {{ .Values.nginxConfig.server.location.root }};
          index {{ .Values.nginxConfig.server.location.index }};
        }
      }
    }
  index.html: |
    {{ .Values.customHtml | nindent 4 }}